// Indonesian (Bahasa Indonesia) content mirror of lib/site.ts.
// Structure and keys (slug, icon, visual, tags, label) must stay identical to
// the English version — only human-readable copy is translated here.
import type { Solution, Project, WorkLabel } from "./site";

export const tagline = "Orbit Operasi yang Cerdas";

export const navLinks = [
  { label: "Tentang", to: "/about" },
  { label: "Solusi", to: "/solutions" },
  { label: "Karya Kami", to: "/our-work" },
  { label: "Klien", to: "/clients" },
  { label: "Proses", to: "/process" },
  { label: "Katalog", to: "/catalogue" },
  { label: "Kontak", to: "/contact" },
];

export const industries = [
  "UKM",
  "Pabrik",
  "Pertanian",
  "Perkebunan",
  "Sekolah",
  "Institusi",
  "Bengkel",
  "Bisnis F&B",
  "Cold Storage",
  "Distributor",
  "Jasa Profesional",
  "Klinik & Salon",
  "Kontraktor",
];

export const solutions: Solution[] = [
  {
    slug: "web-digital-presence",
    name: "Website & Kehadiran Digital",
    icon: "Globe",
    promise: "Terlihat kredibel. Mudah ditemukan. Menghasilkan konversi.",
    oneLiner: "Website profesional dan fondasi digital yang mencerminkan kapasitas bisnis Anda yang sesungguhnya.",
    whatItIs: "Website custom dan fondasi digital yang dibangun untuk mengkonversi dan bertahan lama.",
    whoFor: "UKM, jasa profesional, dan institusi yang membutuhkan kehadiran online yang serius.",
    problems: [
      "Website ketinggalan zaman atau belum ada",
      "Visibilitas pencarian yang rendah",
      "Tidak ada cara jelas bagi pelanggan untuk bertanya",
      "Brand yang terlihat lebih kecil dari bisnis sesungguhnya",
    ],
    whatWeBuild: ["Website responsif", "Manajemen konten", "Formulir lead-capture", "Integrasi katalog", "Dasar-dasar SEO", "Analitik"],
  },
  {
    slug: "business-systems",
    name: "Sistem Bisnis Kustom",
    icon: "Boxes",
    promise: "Perangkat lunak yang sesuai dengan cara kerja Anda.",
    oneLiner: "Perangkat lunak kustom yang dibentuk sesuai operasi spesifik — termasuk dasbor dan laporan yang Anda butuhkan.",
    whatItIs: "Alat internal yang menggantikan spreadsheet dan kertas dengan satu sumber data yang akurat, lengkap dengan pelaporan yang jelas.",
    whoFor: "Distributor, bengkel, dan UKM yang mulai kewalahan dengan spreadsheet.",
    problems: ["Data dimasukkan ulang di banyak file", "Kekacauan versi", "Tidak ada satu sumber data yang akurat", "Proses manual yang tidak dapat berkembang", "Tidak ada visibilitas real-time terhadap angka"],
    whatWeBuild: [
      "Kontrol inventaris dan stok",
      "Catatan dan alur kerja",
      "Peran, persetujuan, dan panel admin",
      "Dasbor KPI dan tampilan analitik",
      "Ekspor dan laporan terjadwal (termasuk PDF)",
      "Ringkasan keuangan, pajak, dan operasional",
      "Integrasi dengan tools yang sudah Anda gunakan",
    ],
  },
  {
    slug: "automation-iot-monitoring",
    name: "Otomasi & Monitoring IoT",
    icon: "RadioTower",
    promise: "Tangkap masalah sebelum merugikan Anda.",
    oneLiner: "Sensor, otomasi, dan monitoring yang menangkap masalah sebelum menjadi kerugian.",
    whatItIs: "Sensor terhubung, dasbor, dan notifikasi yang memantau kondisi penting — termasuk CCTV dan monitoring lokasi bila relevan.",
    whoFor: "Pabrik, cold storage, dan fasilitas yang bergantung pada kondisi yang stabil.",
    problems: ["Pengecekan dan pencatatan manual", "Masalah baru diketahui setelah terlambat", "Tugas berulang yang menyita waktu staf", "Tidak ada catatan kejadian", "Tidak ada visibilitas lokasi saat tidak ada orang"],
    whatWeBuild: [
      "Feed sensor real-time",
      "Notifikasi ambang batas (SMS / WhatsApp / email)",
      "Tugas dan rutinitas otomatis",
      "Integrasi monitoring CCTV dan kamera",
      "Log dan riwayat kejadian",
      "Aturan eskalasi",
    ],
  },
  {
    slug: "agriculture-plantation-monitoring",
    name: "Monitoring Pertanian & Perkebunan",
    icon: "Sprout",
    promise: "Visibilitas lapangan, dari mana saja.",
    oneLiner: "Visibilitas tingkat lapangan untuk pertanian dan perkebunan, dari mana saja.",
    whatItIs: "Monitoring kondisi, peralatan, dan hasil panen — dipetakan dan dipantau secara real-time.",
    whoFor: "Pertanian, perkebunan, dan estate yang mengelola lahan dan aset dalam skala besar.",
    problems: ["Kondisi diperiksa dengan berjalan kaki", "Masalah baru terdeteksi setelah terlambat", "Catatan yang tersebar", "Sulit melihat keseluruhan estate sekaligus"],
    whatWeBuild: ["Sensor lingkungan", "Pemetaan lahan / estate", "Dasbor status", "Notifikasi", "Catatan hasil panen dan aktivitas"],
  },
  {
    slug: "factory-facility-monitoring",
    name: "Monitoring Pabrik & Fasilitas",
    icon: "Factory",
    promise: "Visibilitas real-time di seluruh area produksi.",
    oneLiner: "Visibilitas real-time di seluruh lantai pabrik dan kondisi fasilitas.",
    whatItIs: "Monitoring peralatan, suhu, downtime, dan keamanan lokasi, dalam satu tampilan.",
    whoFor: "Manufaktur, operator cold storage, dan manajer fasilitas.",
    problems: ["Downtime yang tidak terduga", "Risiko rantai dingin", "Ronde pemeriksaan manual", "Tidak ada peringatan dini", "Data peralatan yang terpecah-pecah", "Visibilitas keamanan lokasi yang terbatas"],
    whatWeBuild: ["Monitoring peralatan dan suhu", "Notifikasi downtime", "Status lantai produksi real-time", "Integrasi monitoring CCTV dan akses", "Pelaporan", "Riwayat perawatan"],
  },
  {
    slug: "education-stem-solutions",
    name: "Solusi Pendidikan & STEM",
    icon: "GraduationCap",
    promise: "Ubah teori menjadi hal yang bisa dibangun siswa.",
    oneLiner: "Portal digital dan platform STEM terapan untuk sekolah dan institusi.",
    whatItIs: "Portal pembelajaran dan platform STEM/robotika praktis yang mengubah teori menjadi praktik.",
    whoFor: "Sekolah, politeknik, dan institusi yang membangun laboratorium nyata sesuai standar industri.",
    problems: ["AI / robotika hanya diajarkan lewat slide", "Kit DIY yang terpecah-pecah", "Perangkat laboratorium yang ketinggalan zaman", "Kesenjangan antara teori dan keterampilan praktis yang terverifikasi"],
    whatWeBuild: ["Portal pembelajaran", "Dasbor monitoring", "Kurikulum STEM terapan", "Jalur pembelajaran berbasis milestone"],
  },
  {
    slug: "service-sector-systems",
    name: "Sistem Digital Sektor Jasa",
    icon: "Sparkles",
    promise: "Kelola booking, pekerjaan, dan klien dari satu tempat.",
    oneLiner: "Sistem booking, penjadwalan, dan manajemen klien untuk bisnis berbasis jasa.",
    whatItIs: "Sistem digital untuk klinik, salon, kontraktor, dan bisnis jasa lain untuk mengelola booking, pekerjaan, dan klien.",
    whoFor: "Klinik, salon, kontraktor, dan bisnis jasa operasional lainnya.",
    problems: ["Booking dicatat lewat telepon atau kertas", "Booking ganda dan janji temu terlewat", "Tidak ada catatan riwayat klien atau pekerjaan", "Tidak ada visibilitas monitoring lokasi/fasilitas bila relevan"],
    whatWeBuild: ["Sistem booking dan penjadwalan", "Catatan klien dan pekerjaan", "Manajemen staf dan sumber daya", "Integrasi monitoring fasilitas dan CCTV bila relevan", "Pengingat dan notifikasi"],
  },
];

export const processSteps = [
  { title: "Memahami operasi Anda", body: "Bagaimana bisnis benar-benar berjalan, di lapangan." },
  { title: "Memetakan masalah", body: "Di mana waktu, data, dan uang terbuang." },
  { title: "Merancang sistem", body: "Rencana yang jelas, dibentuk sesuai alur kerja Anda." },
  { title: "Membangun fase pertama", body: "Mulai fokus, hasilkan sesuatu yang benar-benar berfungsi." },
  { title: "Menguji dan menyempurnakan", body: "Validasi terhadap penggunaan nyata." },
  { title: "Melatih dan serah terima", body: "Tim Anda benar-benar bisa menjalankannya." },
  { title: "Dukungan dan pengembangan", body: "Menjaga sistem tetap andal dan terus berkembang." },
];

export const scopingNote =
  "Setiap proyek disesuaikan dengan operasi, kebutuhan, dan kompleksitas sistem Anda — kami tidak mempublikasikan harga tetap.";

export const differentiators = [
  { title: "Dibangun dari operasi nyata", body: "Sistem dirancang dari alur kerja sesungguhnya, bukan template." },
  { title: "Disiplin engineering + software modern", body: "Keandalan engineering dengan kecepatan tooling modern." },
  { title: "Cakupan menyeluruh", body: "Website, sistem, otomasi, IoT, dan monitoring fasilitas dalam satu mitra." },
  { title: "Proses berbasis pemahaman", body: "LUNAR memahami operasi Anda sebelum membangun apa pun." },
  { title: "Jujur dan terukur", body: "Demo vs. hasil kerja nyata selalu diberi label jelas; setiap proyek disesuaikan dengan klien." },
];

export const clientSegments = [
  "UKM",
  "Pabrik",
  "Pertanian & Perkebunan",
  "Sekolah & Institusi",
  "Bengkel",
  "F&B dan Cold Storage",
  "Bisnis Profesional",
  "Distributor",
  "Bisnis Sektor Jasa",
];

export const projects: Project[] = [
  {
    slug: "company-website-build",
    title: "Pembuatan Website Perusahaan",
    category: "Website & Kehadiran Digital",
    label: "Demo" as WorkLabel,
    tags: ["web"],
    visual: "devices",
    problem: "Brand yang terlihat lebih kecil secara online dibanding bisnis sesungguhnya.",
    solutionText: "Website profesional dan responsif dengan lead capture dan jalur pertanyaan yang jelas.",
    value: "Kehadiran yang kredibel dan mengkonversi pengunjung menjadi pertanyaan bisnis.",
    features: ["Desain responsif", "Formulir lead-capture", "Integrasi katalog", "Dasar-dasar SEO"],
    liveUrl: "https://lumaradesign.netlify.app/",
  },
  {
    slug: "custom-business-system",
    title: "Sistem Bisnis Kustom",
    category: "Sistem Bisnis",
    label: "Demo" as WorkLabel,
    tags: ["business systems"],
    visual: "dashboard",
    problem: "Stok dan catatan dilacak lewat spreadsheet, dengan masalah baru diketahui setelah terlambat.",
    solutionText: "Sistem inventaris dan catatan real-time dengan dasbor langsung dan notifikasi stok rendah.",
    value: "Satu sumber data yang akurat, menggantikan spreadsheet yang rapuh.",
    features: ["Tingkat stok real-time", "Dasbor KPI", "Notifikasi ambang batas stok rendah", "Laporan yang dapat diekspor"],
    // TODO: isi liveUrl di sini setelah baja-makmur-erp-v2 di-deploy, contoh:
    // liveUrl: "https://baja-makmur-erp.netlify.app/",
  },
  {
    slug: "automation-iot-wip",
    title: "Otomasi & Monitoring IoT",
    category: "Otomasi & IoT",
    label: "In Progress" as WorkLabel,
    tags: ["automation-iot"],
    visual: "wip",
    problem: "Area solusi ini masih dalam pengembangan aktif.",
    solutionText: "Kami sedang membangun prototipe monitoring sensor dan otomasi pertama kami.",
    value: "Silakan cek kembali nanti, atau diskusikan kebutuhan spesifik Anda langsung dengan kami.",
    features: ["Dalam pengembangan"],
  },
  {
    slug: "agriculture-wip",
    title: "Monitoring Pertanian & Perkebunan",
    category: "Pertanian",
    label: "In Progress" as WorkLabel,
    tags: ["agriculture"],
    visual: "wip",
    problem: "Area solusi ini masih dalam pengembangan aktif.",
    solutionText: "Kami sedang membangun prototipe monitoring lapangan dan perkebunan pertama kami.",
    value: "Silakan cek kembali nanti, atau diskusikan kebutuhan spesifik Anda langsung dengan kami.",
    features: ["Dalam pengembangan"],
  },
  {
    slug: "factory-wip",
    title: "Monitoring Pabrik & Fasilitas",
    category: "Pabrik",
    label: "In Progress" as WorkLabel,
    tags: ["factory"],
    visual: "wip",
    problem: "Area solusi ini masih dalam pengembangan aktif.",
    solutionText: "Kami sedang membangun prototipe monitoring pabrik dan fasilitas pertama kami.",
    value: "Silakan cek kembali nanti, atau diskusikan kebutuhan spesifik Anda langsung dengan kami.",
    features: ["Dalam pengembangan"],
  },
  {
    slug: "education-wip",
    title: "Solusi Pendidikan & STEM",
    category: "Pendidikan",
    label: "In Progress" as WorkLabel,
    tags: ["education"],
    visual: "wip",
    problem: "Area solusi ini masih dalam pengembangan aktif.",
    solutionText: "Kami sedang membangun prototipe portal pembelajaran dan STEM terapan pertama kami.",
    value: "Silakan cek kembali nanti, atau diskusikan kebutuhan spesifik Anda langsung dengan kami.",
    features: ["Dalam pengembangan"],
  },
  {
    slug: "service-sector-wip",
    title: "Sistem Digital Sektor Jasa",
    category: "Sektor Jasa",
    label: "In Progress" as WorkLabel,
    tags: ["service-sector"],
    visual: "wip",
    problem: "Area solusi ini masih dalam pengembangan aktif.",
    solutionText: "Kami sedang membangun prototipe booking dan manajemen klien pertama kami.",
    value: "Silakan cek kembali nanti, atau diskusikan kebutuhan spesifik Anda langsung dengan kami.",
    features: ["Dalam pengembangan"],
  },
];

export const workFilters = [
  { label: "Semua", value: "all" },
  { label: "Web", value: "web" },
  { label: "Sistem Bisnis", value: "business systems" },
  { label: "Otomasi / IoT", value: "automation-iot" },
  { label: "Pertanian", value: "agriculture" },
  { label: "Pabrik", value: "factory" },
  { label: "Pendidikan", value: "education" },
  { label: "Sektor Jasa", value: "service-sector" },
];
